### ISSUE TITLE
Support for AWS EC2 IMDSv2

### ISSUE THREAD

**Issue by justincjohnson** [aws-beam/aws_credentials#13]
Hi,

I'm using AWS's Security Hub service, and it recently created a finding for my environment, specifically `[EC2.8] EC2 instances should use IMDSv2`.  The remediation details can be found at https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation, but in short, the new version of the service requires an extra API call to generate a token, and then subsequent API calls need to pass that token in a header.

I'm new to this project and thought I'd start by asking if you are aware of this change to IMDS and if anyone is already planning on making the corresponding code changes in the project.  I'm willing to roll up my sleeves, but given that I'm new here, I thought I'd start with just bringing up the issue and starting a discussion.

Thanks for the projects you've created here.  I'm just gaining familiarity but I like the idea of clients that uses code gen.

**Comment by justincjohnson** [comment]
In case helpful, note that I opened a [draft PR](https://github.com/ex-aws/ex_aws/pull/739) for `ex_aws` that demonstrates what a solution might look like.

**Comment by mrallen1** [comment]
Hello - I was unaware of IMDSv2 - but adding to this project sounds great. I would appreciate a PR implementing it if you have time/desire to do so. Thanks!

**Comment by bernardd** [comment]
> I'm new to this project and thought I'd start by asking if you are aware of this change to IMDS and if anyone is already planning on making the corresponding code changes in the project. I'm willing to roll up my sleeves, but given that I'm new here, I thought I'd start with just bringing up the issue and starting a discussion.

New or not, you're absolutely more than welcome to offer an implementation for this. As I mentioned in the PR, I'm not actually familiar with the system involved, but at a glance it looks like something that ex_aws would definitely benefit from supporting.

**Comment by justincjohnson** [comment]
@bernardd did you mean to only comment in the `ex_aws project`?  It looks like you may have accidentally crossed over into the `aws-beam/aws-elixir` project, perhaps thinking this was an `ex_aws` issue referencing the draft PR?  If so, understandable given the nature of my comments above.

**Comment by bernardd** [comment]
Oh man, I have no idea how I managed that. Jumping around between too many issues last night. Apologies.

**Comment by justincjohnson** [comment]
I've created a draft PR at https://github.com/aws-beam/aws_credentials/pull/14 and would love some feedback.  As I note on the PR, this is basically my first Erlang code, so no doubt it can be improved.  I tested in AWS on an Amazon Linux instance.

One thing I'm currently assuming and need to verify is that V2 of IMDS is always available currently.  In my experience so far that is true.  Amazon enables both the less secure v1 and the new and improved v2, but I assume v1 will go away eventually.  If the assumption is correct that v2 is always available effective immediately, it seemed better to just have the code use v2 instead of checking config or something to decide if it should use v1.

Thanks in advance.

**Comment by justincjohnson** [comment]
After re-reading https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/ it seems to me that the decision to only support V2 makes sense.

**Comment by mrallen1** [comment]
Hey, I meant to review this over the weekend but I just didn't get a chance yet. I will try to get to it in the next day or two - in any case, I appreciate you writing this. Thank you!

**Comment by mrallen1** [comment]
@nalundgaard @motobob you may be interested in this PR too

**Comment by justincjohnson** [comment]
@mrallen1 any update on this by chance?

**Comment by mrallen1** [comment]
I think once we get #20 squared up, we can merge this pretty quickly. Yeah, I'm sorry it's taken a  long time

**Comment by justincjohnson** [comment]
No worries. I’m just now getting near the time when I truly need the changes, so timing is still good here. 

Also, if you need to make any changes to the PR I don’t mind at all if I don’t get credit for the changes. I’m just trying to do my part to get the functionality added. Thanks for your time.

**Comment by mrallen1** [comment]
Just merged #14, so I'm going to close this.
