### ISSUE TITLE
Should we keep compatibility with OTP 20?

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws_credentials#21]
@mrallen1 The `aws_credentials` module contains a un-hygienic macro (in the sense that relies on a variable which is defined outside of its scope) and that is supposed to keep backward compatibility with OTP 20 or older. Given that OTP 20 is from 2017, what's your view on dropping compatibility?

**Comment by robertoaloi** [comment]
One argument to drop that compatibility is that we could replace the usages of `error_logger` in favour of the built-in `logger`.

**Comment by mrallen1** [comment]
Drop it like it's hot
