### ISSUE TITLE
Add option to not scare the shit out of developers with stacktraces on expected crashes

### ISSUE THREAD

**Issue by netrome** [aws-beam/aws_credentials#22]
As a developer using `aws_credentials` I would like the ability to run the application locally without any providers configured, and not get a huge exception stack trace in my logs that steals unnecessary focus.

**Comment by mrallen1** [comment]
ok that seems like a valid use case to me but I think we're going to adopt OTP's logger

**Comment by netrome** [comment]
Sounds like a sensible decision that will also solve this use case.
