### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws_credentials#27]
Let's introduce the Elvis linter, so we can start working with consistent style.

**Comment by mrallen1** [comment]
I have no objection but aesthetically I don't care for the "comma first" list style.

**Comment by robertoaloi** [comment]
I'm used to it, but don't have strong feelings about it. Happy to use a formatter so style is not an issue.

**Comment by mrallen1** [comment]
@robertoaloi can this be closed now?

**Comment by robertoaloi** [comment]
Indeed. Elvis is run as part of the CI pipeline.
