### ISSUE TITLE
Publish the application to Hex

### ISSUE THREAD

**Issue by robertoaloi** [aws-beam/aws_credentials#30]

**Comment by mrallen1** [comment]
Try to get to that today - who else needs to be an owner on this project on hex to make this work?

**Comment by robertoaloi** [comment]
I can suggest @jfacorro

**Comment by robertoaloi** [comment]
One issue when publishing to Hex is that one of the dependencies (`eini`) is not found in Hex. I guess this is due to the fact we use a fork. What's the plan? Do we try to keep the fork up to date and publish that too or we just drop it and use upstream `eini`? I can totally see the reasoning behind the fork of `eini`, just not sure if it's worth maintaining a fork.

**Comment by robertoaloi** [comment]
Happy with that, but then let's call it `eini-mini` or something :)

**Comment by robertoaloi** [comment]
Also, since I don't have access to Hex, would you mind publishing also `aws-erlang`? I would also like to produce and publish the docs for it, but I'm having issues with `rebar3 docs`:

https://hexdocs.pm/aws_erlang/

**Comment by aleDsz** [comment]
So, to publish this package, the issue #35 is a "must have", right?

Might some other points would be interesting before publishing, and would be cool to get some feedback about:

- [ ] Read shared configuration file (`~/.aws/config`) ([issue comment](https://github.com/aws-beam/aws-elixir/issues/109#issuecomment-1006055224))
  - Get `session token` (#37) and `region`
- [ ] Read an Erlang env to avoid logging fetching errors (not only `:fail_if_unavailable`)
- [ ] Read an Erlang env to avoid starting the `aws_credentials_app`

WDYT?

**Comment by aleDsz** [comment]
Add support for region env without token env (#38)

this is a particular case, would love some feedback.

**Comment by aleDsz** [comment]
@jadeallenx @jkakar @jfacorro Sorry for pinging, but is this repo still maintained? If so, could help us to make this project ready for publishing to hex?

**Comment by onno-vos-dev** [comment]
@aleDsz Took the liberty of updating your check list by tickboxing the merged PRs :+1:

**Comment by philss** [comment]
Hi everyone :wave: 

I work with @aleDsz and since I have access to the repository, I was thinking in go ahead and handle the publishing of the package.

I'm planning to follow what @jadeallenx suggested, with the name @robertoaloi suggested and publish the fork of `eini` first.
Also I can add you as owners/publishers as you wish :)

If you have anything against this, please let me know. Thanks!

**Comment by jadeallenx** [comment]
I would appreciate being added as a co-owner, please.

**Comment by jadeallenx** [comment]
I intended to publish eini-mini but it required a ton of yak-shaving I was unprepared to take on/see through. I can't remember the specifics right now though.

**Comment by aleDsz** [comment]
@jadeallenx When u have some time, could u post the ToDo list to prepare `eini-mini` to be published? I would like to make some contributions to publish both packages

**Comment by josevalim** [comment]
I believe this can be closed. :)

**Comment by josevalim** [comment]
Closing this for now, I think sso and web credentials can be added by interested parties. :)
