### ISSUE TITLE
EC2 provider fails when an API is available at the IP requested, but a 400 returns

### ISSUE THREAD

**Issue by tom-con** [aws-beam/aws_credentials#36]
Hi, running into this issue when testing some elixir code in the Github workflow. The worflows run on some Azure servers, but apparently the http://169.254.169.254 is available on these servers for some microsoft purposes. This causes:
```erlang
-spec fetch_session_token() -> {ok, session_token()}.
fetch_session_token() ->
  RequestHeaders = [{?SESSION_TOKEN_TTL_HEADER, ?SESSION_TOKEN_TTL_SECONDS}],
  {ok, 200, Body, _Headers} =
    aws_credentials_httpc:request(put, ?SESSION_TOKEN_URL, RequestHeaders),
  {ok, Body}.
```
to fail.  Since there's no match for a 400 as evidenced:
```bash
** (Mix) Could not start application aws_credentials: :aws_credentials_app.start(:normal, []) returned an error: shutdown: failed to start child: :aws_credentials
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:ok, 400, "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n    <Code>InvalidHttpVerb</Code>\n    <Message>The HTTP verb specified was not recognized by the server.</Message>\n    <Details>'PUT' is not a supported verb.</Details>\n</Error>", [{'date', 'Tue, 17 May 2022 16:25:43 GMT'}, {'server', 'Microsoft-IIS/10.0'}, {'content-length', '322'}, {'content-type', 'text/xml; charset=utf-8'}]}
```

I would expect this to simply fail to return credentials for the provider, rather than break the application start.

Am I thinking about this wrong? Would appreciate any advice.

**Comment by onno-vos-dev** [comment]
Hi @tom-con not ignoring your issue but will try to investigate over the next few days and get back to you :+1: Just wanted to let you know so you don't feel ignored :slightly_smiling_face:

**Comment by tom-con** [comment]
@onno-vos-dev Thanks so much!

**Comment by paulo-ferraz-oliveira** [comment]
This bit me today. Any way I can help make this move forward (e.g. pull request)? In a CI environment, I'm running with a test profile, which does `_ec2` first and `_env` second (as per my actual requirements), but it crashes as indicated for this issue, so I don't get to test `_env` second 😭.

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna pull request. `aws_credentials_ec2:fetch/1` mentions returning `{error, _}` but it never does, per implementation.
