### ISSUE TITLE
`get_credentials` can return `undefined` on error

### ISSUE THREAD

**Issue by kevinkirkup** [aws-beam/aws_credentials#56]
I've noticed that the dialyzer will return an error when calling `get_credentials()` saying
```
The pattern can never match the type.

Pattern:
:undefined

Type:
%{
  :access_key_id => binary(),
  :credential_provider => _,
  :secret_access_key => binary(),
  :region => binary(),
  :token => binary()
}
```
But we have observed that it does return `:undefined` in failure cases.
This is being called from Elixir. Not sure if that should matter though.

https://github.com/aws-beam/aws_credentials/blob/d923af741bee6949f5d2257d8b6778321530d7e3/src/aws_credentials.erl#L98

**Comment by josevalim** [comment]
Correct. If `fail_if_unavailable` is set to false, then it can return `undefined`. However, I am thinking that `fail_if_unavailable` is an anti-pattern here. I would rather return undefined and let users check in their app boot if the credentials are missing and how they want to act. Thoughts @onno-vos-dev?

**Comment by onno-vos-dev** [comment]
I agree with you @josevalim but that would be a pretty backwards breaking to remove the functionality that this provides. I'm happy to take a look on the weekend and see what I can come up with 👌

I'd propose in that case to make the change and do a bump to 1.0.0 as a released version. Despite some additional features needed for aws_credentials it's definitely in a good enough shape for a major version in my eyes.

**Comment by josevalim** [comment]
@onno-vos-dev I can send a PR if you are ok with it. Perhaps we ship v0.2.0 for one last round of testing and then ship a major version?

**Comment by onno-vos-dev** [comment]
Sounds good to me too 👌 @josevalim
