### ISSUE TITLE
Is log_errors_immediately correct?

### ISSUE THREAD

**Issue by josevalim** [aws-beam/aws_credentials#58]
The documentation says:

> If you prefer to not log errors as they happen (the default behavior), but accumulate them for later, you can set erlang environment variable log_errors_immediately to false as in this example

However, both cases log immediately, except one uses ?LOG_INFO and the other uses ?LOG_ERROR. Is that intentional? Maybe `log_level` would be a better config name? Or maybe we just discard the config altogether?

**Comment by onno-vos-dev** [comment]
I've allocated some time in the weekend to take a look at this 👌

**Comment by josevalim** [comment]
@paulo-ferraz-oliveira you were the one who requested the feature, but I believe PR #59 also achieves what you want, but without a need for the option. I will send a PR and, if you are both happy with it, we can merge. :)

**Comment by josevalim** [comment]
@onno-vos-dev we have been running a fork with my PRs merged and it has all be good. Shall we merge them and ship a new release? :) Thank you!

**Comment by onno-vos-dev** [comment]
@josevalim Whoops! My bad! Merged both PR's 👍 Will tag a release in a few minutes so it can go through the release train👌

**Comment by onno-vos-dev** [comment]
0.2.0 released 👌 👍 @josevalim

**Comment by paulo-ferraz-oliveira** [comment]
@josevalim, I missed this notification in Nov 😢, but thanks for reaching out. I'm not using this anymore, at the moment, but believe the achieved effect is similar to my initial goal, yes. Also, thanks for the release @onno-vos-dev. Cheers.
