### ISSUE TITLE
Bump jsx to 3.1.0

### ISSUE THREAD

**Issue by sergioruiz-jt** [aws-beam/aws_credentials#68]
We are currently experiencing dependency conflicts in our project due to the version of the JSX library we are using. To resolve these conflicts, we require an upgrade to at least version 3.1.0 of the JSX library.

Could you please consider bumping the version of the JSX package to a minimum of 3.1.0?

**Comment by onno-vos-dev** [comment]
@sergioruiz-jt Create the PR and I'll merge it before the sun sets 👍 😄

**Comment by onno-vos-dev** [comment]
Actually, I'll create the PR as eini-beam also needs to bumped in `rebar.lock`

**Comment by onno-vos-dev** [comment]
@sergioruiz-jt Release 0.2.3 is out: https://hex.pm/packages/aws_credentials/0.2.3
